### ISSUE TITLE
Should this script start by dropping all users except the current user?

### ISSUE THREAD

**Issue by Alex-Yates** [Alex-Yates/PowerShell_GeneratePermissions#3]
This will ensure that any additional users are not persisted. However, it might upset people who get revoked!

Perhaps this be implemented in the form of a drift check, rather than a forced drop? Raising an error or warning if any additional users exist that shouldn't?

**Comment by paschott** [comment]
Maybe an option to drop/recreate existing users, ignore ones not in the script, or similar? We did that because we had some security issues that needed to be addressed so the drop/create made sense. I can see value in _not_ doing that unless needed.  But that's the whole "we want the DB to look like this" aspect.

**Comment by Alex-Yates** [comment]
Going to implement an optional switch to delete all additional users, but to leave existing users.

**Comment by Alex-Yates** [comment]
Resolved with 534bb857cc54fd40f07418c58eccb806d3d36075

Only implemented in PowerShell, using dbaTools.
Optionally, users can decide to drop users not included in file.
Note, this does not redeply existing users since that might cause problems. Need to update them rather than drop/create. Creating a separate issue for that.
